[programs.localnet]
todo = "6NnowxYkaDjz7sto1RnuWgHreXZh7pNhHmNLL355m88U"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
