[programs.localnet]
blog = "82JVKb1ABeDTNyhid48FLPaYZVscMhXy8rzFEVBjy544"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
